### ISSUE TITLE
Push footer to bottom of page

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/leafwing-website#135]
It looks awkward when the footer is not at the bottom of the page when the content doesn't fill the whole page:
![Screenshot of the main page where the footer floats in the middle of the page](https://user-images.githubusercontent.com/13908946/174488926-53c3c5c7-b93f-41b6-a785-e32cf8e40b7d.png)

This can be fixed using flexbox, e.g.
```html
<header>
  <!-- Header -->
</header>

<main>
  <!-- Content -->
</main>

<footer>
  <!-- Footer -->
</footer>
```

```css
html {
  height: 100%;
}

body {
  height: 100%;
  display: flex;
  flex-flow: column;
  
  margin: 0;
  padding: 0;
}

main {
  flex-grow: 1;
}
```

This will make sure the footer stays at the bottom, but doesn't float over the content when it fills the page.

[Fiddle playground](https://jsfiddle.net/drshagvj/2/)
