### ISSUE TITLE
Add dynamic dark theme

### ISSUE THREAD

**Issue by TimJentzsch** [Leafwing-Studios/leafwing-website#140]
This would be a miscellaneous feature that doesn't provide much value, but I love dark themes so I'll suggest it anyway :P

Essentially, the browser tells you which theme the user prefers to use and you can use that information to adapt the website's theme efficiently (and with pure CSS -- no scripting needed!)

This is how to do this with pure CSS (your framework might make it easier):

1. Define the colors you want to use by default as CSS variables:
    ```css
    :root {
      --background-color: #f7f4ed;
      --primary-color: #709970;
      --text-color: black;
      /* ... */
    }
    ```
2. Overwrite the CSS variables depending on the non-default theme:
    ```css
    @media (prefers-color-scheme: dark) {
      :root {
        --background-color: #121212;
        --primary-color: #709970;
        --text-color: white;
        /* ... */
      }
    }
    ```
3. Use the CSS variables every time you want to use a color:
    ```css
    body {
      background-color: var(--background-color);
      color: var(--text-color);
   }
   ```

That's it! Now the browser will render the website in the color scheme that the user prefers (usually the system's theme).

You can preview the changes using the button in Firefox Dev Tools:
![Theme switching buttons in Firefox Dev Tools](https://user-images.githubusercontent.com/13908946/174490257-523615bf-c92d-4836-8e96-6a40019e0f7f.png)

As you can see it switches instantly and you don't first preload the wrong theme, as it sometimes happens with JS themes.

[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

Bonus fact: This even works in SVG, e.g. you can change your website's favicon dependent on the theme! See [this blog](https://catalin.red/svg-favicon-light-dark-theme/) for an example.
